### PR TITLE
the reviewed changes

### PR DESCRIPTION
**Pull request by CharuChhimpa**
The changes mentioned are done in this branch.

### CODE REVIEW

**Comment by CharuChhimpa** [comment]
Pratyush check this out. I have made all the required changes.

**Comment by singhpratyush** [comment]
I apologize for late response. Will do it right away.

**Comment by singhpratyush** [comment]
@prsntmaurya : Please review the pull request.

**Comment by prsntmaurya** [comment]
@CharuChhimpa : Please give image credits if image is not stock image for all the images used.

**Review by prsntmaurya — CHANGES_REQUESTED** [review]
Use stock images.

**Pull request closed without merging**
